on: push
name: TOC Generator
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate HTML
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path-to-your-generated-files  # Substitua pelo caminho correto
          publish_branch: gh-pages  # Certifique-se de que o branch gh-pages está correto
